# Generated by Django 4.0.3 on 2022-12-03 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_perevaladded_remove_perevaldata_coords_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PerevalAreas',
        ),
    ]
