# Generated by Django 4.0.3 on 2022-12-04 03:04

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_level_perevaladded_level_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perevalimages',
            old_name='img',
            new_name='data',
        ),
        migrations.AlterField(
            model_name='users',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
