# Generated by Django 4.0.3 on 2022-12-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_img_perevalimages_data_alter_users_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perevaladded',
            name='connect',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
