# Generated by Django 4.0.3 on 2022-12-04 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_coord_id_perevaladded_coord_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perevaladded',
            old_name='coord',
            new_name='coords',
        ),
    ]
