# Generated by Django 4.0.3 on 2022-12-04 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_rename_coord_perevaladded_coords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perevalimages',
            name='pereval_added',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.perevaladded'),
        ),
    ]
